### ISSUE TITLE
[Request] allow "RemoveInteriorFog" to apply to asteroid-13

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-HalloweenTheme#1]
Hey there,

I saw today that you created the mod "RemoveInteriorFog" to address the v67 update, and it's excellent.  We've had concerns about the interior fog associated with Wesley's moon Asteroid-13 prior to this update.  The functionality is similar enough that it seems worth asking.

Would it be possible to extend the "RemoveInteriorFog" to also remove the interior fog on Asteroid-13?  It is even thicker/worse than the v67 update and makes navigating the interiors essentially impossible.

Either way, thanks for the mod.  It's been very helpful :)

![image](https://github.com/user-attachments/assets/d6d2fc71-6393-462f-bafa-391ee8177c62)
![image](https://github.com/user-attachments/assets/93fdb06c-dd4c-46f3-b350-d699fbe4e07c)

**Comment by ZehsTeam** [comment]
@ajsglist This has been added in [RemoveInteriorFog](https://thunderstore.io/c/lethal-company/p/Zehs/RemoveInteriorFog/) v1.0.1+

You will need to enable `DisableOtherInteriorFog` in the config settings.

I have also created a GitHub repo for this mod.
https://github.com/ZehsTeam/Lethal-Company-RemoveInteriorFog

**Comment by JohnMetroid** [comment]
ahhhhhhhhhh, amazing

![image](https://github.com/user-attachments/assets/e782f178-d289-4d0b-aea5-ef8e74f2e957)
